### PR TITLE
Epic 156 unread alerts

### PR DESCRIPTION
**Pull request by jakubsolecki**
https://github.com/agh-docker-monitoring/dockiera-app/issues/156

### CODE REVIEW

**Comment by kraleppa** [comment]
Konfilkt masz  -.-

**Comment by jakubsolecki** [comment]
@skupien you can adjust frontend now

**Comment by skupien** [comment]
unread alerts completed

**Review by skupien — APPROVED** [review]
great job @skupien @jakubsolecki

**Pull request merged**
