### PR TITLE
dialog changed and routes refactor

### PR DESCRIPTION
**Pull request by kraleppa**
dialog moved to the seperate route
it still needs refactor

### CODE REVIEW

**Comment by kraleppa** [comment]
I decided to remove some dead code from frontend.

Also I moved addHost dialog to seperate route /addDialog, so now we can use useForm hook on it

**Comment by kraleppa** [comment]
uhh...
 and I removed the sidebar as we discussed previously

**Comment by kraleppa** [comment]
Screenshot 2021-09-06 at 18 25 18
Screenshot 2021-09-06 at 18 26 10

**Comment by jakubsolecki** [comment]
https://github.com/agh-docker-monitoring/dockiera-app/issues/39

**Pull request merged**
